### ISSUE TITLE
Installation issue on Mac OS X

### ISSUE THREAD

**Issue by cosimolupo** [qmarcou/IGoR#2]
First of all, congratulations for this fantastic software!
Unfortunately, I had a little issue during the installation process on a MacBook Pro 15" (late 2011, OS X version 10.11.6). Indeed, I found that the last step of the installation procedure (namely the `make install` command) aborted after trying to address the share/igor directory into my home:
`mkdir: /Users/lupo/share/igor: No such file or directory`
The same occurred on a newer MacBook laptop, so it would seem to be a general issue when trying to install IGoR on Mac OS X. Notice also that an analogous error occurred when trying to install IGoR in the default place with the administrator privileges.
I found a workaround, that is manually creating that directory and then launching again the `make install` command. IGoR seems to work perfectly now!
Finally, I would suggest the following [guide](https://solarianprogrammer.com/2017/05/21/compiling-gcc-macos/), which I found very useful when trying to install the GNU gcc compiler on Mac OS X directly from the source (i.e. not via MacPorts or HomeBrew).

**Comment by qmarcou** [comment]
Thanks for the guide I have added it to the installation instructions.
As for the rest I am still investigating why the directory has not been created automatically, in the meantime creating it by hand is a good hack.

**Comment by qmarcou** [comment]
Hi @cosimolupo,
I think this issue has been fixed thanks to @smoe, and I have just uploaded a new release implementing this fix along with other new features!
I'll close this issue for now and will reopen it if needed
Best
