### ISSUE TITLE
TRA CDR3 Anchors

### ISSUE THREAD

**Issue by PimEnpicom** [qmarcou/IGoR#24]
Hi qmarcou,

I noticed there are no CDR3 anchors present for TRA (*_gene_CDR3_anchors.csv contains only the headers). Are these anchors available somewhere? If not, do you have some pointers on how to obtain them?

Thanks in advance.

Pim

**Comment by qmarcou** [comment]
Hi Pim,
My apologies for the late reply. I for now do not have the CDR3 alpha anchors for human extracted. These anchors are obtained by using the aligned IMGT genes that are aligned regarding their anchors
Sorry for the brevity I do not currently have access to a computer
