### ISSUE TITLE
Chain IGoR commands

### ISSUE THREAD

**Issue by penuts7644** [qmarcou/IGoR#51]
Hi Quentin,

Is it possible to chain IGoR commands? When I try to run something like this, it seems to work fine...

```
igor -set_wd $WDPATH -batch foo -read_seqs test.txt -species human -chain beta -align --all -evaluate -output --scenarios 10
```

or do I have to separate the commands and run them one by one?

Cheers, Wout

**Comment by qmarcou** [comment]
Hi Wout,
Yes I have designed the command line processing such that you can chain all commands as long as it makes sense, if the provided command line chain makes some operation ambiguous an error will arise and Igor will terminate with an error message.
