### ISSUE TITLE
--pgen fails to error

### ISSUE THREAD

**Issue by jeremycfd** [qmarcou/IGoR#54]
Embarrassed to say I spent more time than I will admit trying to figure out why the `-output --pgen` option was not producing a Pgen_counts.csv file before I finally realized that the command is case-sensitive `-output --Pgen`. Might be worthwhile to report errors when oblivious people like me include subargs and subsubargs that don't exist!

**Comment by qmarcou** [comment]
Hi @jeremycfd,
Sorry about that and thanks for pointing it out! It seems I have indeed forgotten the unknown argument clause on this one... I'll fix it now and check that  I have not forgotten another one elsewhere.
