### ISSUE TITLE
Limiting IGoR's CPU usage

### ISSUE THREAD

**Issue by yttyhhh** [qmarcou/IGoR#63]
![image](https://user-images.githubusercontent.com/51687456/123605112-122d8380-d82e-11eb-9174-8cc956838281.png)

**Comment by qmarcou** [comment]
Dear @yttyhhh ,
Please refer to the [documentation](https://qmarcou.github.io/IGoR/#general-commands-summary) of the general command line arguments.
You can set the number threads ( and hence maximum CPU usage) using the `-threads N` argument, where N is the desired number of threads. The default behavior is to use all available threads. 
best regards
