### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by shwdmsh** [qmarcou/IGoR#64]
Hi,I use these commans as follows to install IGoR ,some error as follows:

include/jemalloc/internal/../jemalloc.h:59:28: error: redefinition of 'aligned_alloc'
 #  define je_aligned_alloc aligned_alloc
                            ^
src/jemalloc.c:1978:1: note: in expansion of macro 'je_aligned_alloc'
 je_aligned_alloc(size_t alignment, size_t size) {
 ^~~~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_internal_decls.h:50:0,
                 from include/jemalloc/internal/jemalloc_preamble.h:5,
                 from src/jemalloc.c:2:
/root/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/stdlib.h:513:21: note: previous definition of 'aligned_alloc' was here
 static inline void* aligned_alloc (size_t al, size_t sz)
   
Could you help me ?
My centos version is 7.0.
Then:
./configure
make(some error)

**Comment by qmarcou** [comment]
Dear @shwdmsh 
It seems you have a conflict with some anaconda C library, however I would need more information to give you some hints.
As it seems you have closed this issue, I guess you found a solution to your problem, could you please write it up here or give hints of the nature of the problem and solutions for other users bumping into this?
Best regards

**Comment by shwdmsh** [comment]
Dear Sir/Madam,


Thank you very much for help!
I have another question.
When I use the command as follows,I can get the full results: 
igor -set_wd $WDPATH -batch foo -species human -chain IGL -align
However,I use the command :
igor -set_wd $WDPATH -batch foo -species human -chain IGL -align ---best_align_only ---best_gene_only
some errors showing:
[IGoR] ERROR: Unknown gene specification"---best_align_only"for -align
[IGoR] ERROR: Use "man igor", "igor -help" or visit https://github.com/qmarcou/IGoR to see available commands and their effects.
How can I get the best align only and the best gene only result?
Thank you for your help!


Best regards









At 2021-07-21 17:46:26, "qmarcou" ***@***.***> wrote:

Dear @shwdmsh
It seems you have a conflict with some anaconda C library, however I would need more information to give you some hints.
As it seems you have closed this issue, I guess you found a solution to your problem, could you please write it up here or give hints of the nature of the problem and solutions for other users bumping into this?
Best regards
