### ISSUE TITLE
wrong default path for genomic templates in 1.2

### ISSUE THREAD

**Issue by pogorely** [qmarcou/IGoR#8]
Hi, Quentin!

version 1.2 seems to crush on demo example, because it looks for genomic templates in wrong place by default. Same code performs fine on previous version. 

`
WDPATH=.
./igor -set_wd $WDPATH -batch foo -species human -chain beta -align --all`

returns following:

`
Batch name set to: foo_
Species parameter set to: human
Chain parameter set to: beta
Working directory set to: "./"
[IGoR] ERROR: Exception caught while reading TRB V genomic templates.
[IGoR] ERROR: File not found: /usr/local/share/igor/models/human/tcr_beta/ref_genome/genomicVs.fasta
`

Best, Misha.

**Comment by pogorely** [comment]
Hi, Quentin!
There is no `/usr/local/share/igor` directory after installation. I attach config.log (is it the right one?)
[config.log](https://github.com/qmarcou/IGoR/files/2000758/config.log)

i've installed by running `./configure CXX=g++-7 CC=gcc-7;make `
it is os x Sierra(10.12), gcc-7 was from homebrew.

Misha

**Comment by qmarcou** [comment]
Hi Misha,
Sorry if i was not clear, I meant creating an installation log file yourself e.g `make install<make_install.log`
However, since ``ddaa=

**Comment by qmarcou** [comment]
Hi Misha!
I think this issue has been fixed thanks to @smoe, and I have just uploaded a new release implementing this fix along with other new features!
I'll close this issue for now and will reopen it if your problem has not been solved by it
Apologies for the long delay
